# Generated by Django 5.1.6 on 2025-04-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('key', models.CharField(max_length=100)),
                ('is_expire', models.BooleanField(default=False)),
                ('is_conf', models.BooleanField(default=True)),
                ('tried', models.IntegerField(default=0)),
            ],
        ),
    ]
