# Generated by Django 5.1.6 on 2025-04-24 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_category_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
